package game;

import game.Enumeration.BlockType;

public class GameMap {
	/*private BlockType[][] map{{BlockType.WALL,BlockType.WALL,BlockType.WALL,BlockType.WALL,BlockType.WALL},
									{BlockType.WALL,BlockType.EMPTY_EMPTY_PATH,BlockType.EMPTY_EMPTY_PATH,BlockType.EMPTY_EMPTY_PATH,BlockType.WALL},
									{BlockType.WALL,BlockType.EMPTY_EMPTY_PATH,BlockType.WALL,BlockType.EMPTY_EMPTY_PATH,BlockType.WALL},
									{BlockType.WALL,BlockType.WALL,BlockType.WALL,BlockType.WALL,BlockType.WALL}},
		*/	
	private int width = 16;
	private int height = 15;
	
	
	
	private BlockType[][] map = {{BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL},


	{BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.WALL},

	{BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL},
	
	{BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL},

	{BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL},
	
	{BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL},
	
	{BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL},
	
	{BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.WALL},
	
	{BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL},

	{BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL},
	
	{BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL},
	
	{BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL},
	
	{BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.WALL},
	
	{BlockType.WALL,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.EMPTY_PATH,
	BlockType.WALL},
	
	{BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL,
	BlockType.WALL}};
	
	
	
	
	
	public int getHeight() {
		return height;
	}
	
	public int getWidth() {
		return width;
	}
	
	public BlockType getBlockAt(int x,int y) {
		return map[y][x];
	}

}
